POST http://localhost:5000/api/profile
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmMGM0ZDQ0YjNiMmZmNDNkYWM2MTUwYiIsImlhdCI6MTU5NDgwOTQ0OSwiZXhwIjoxNTk0ODk5NDQ5fQ.GRs8dy8Ym5AVVM6xQVA9RZYJvaSDQqG4gzf8utYH4vs

{
  "company": "mine",
  "status": "developer",
  "skills": "javascript, blow shit up, ruby",
  "facebook": "face_poo"
}

###
POST http://localhost:5000/api/users
Content-Type: application/json

{
  "name": "test name2",
  "email": "test102@test.com",
  "password": "abc123"
}
###

GET http://localhost:5000/api/profile
Accept: application/json

###
GET http://localhost:5000/api/auth
Accept: application/json

###
GET http://localhost:5000/api/posts
Accept: application/json

###
GET http://localhost:5000/api/users
Accept: application/json

###
GET http://localhost:5000
Accept: application/json

###
