GET http://localhost:5000/api/profile
Accept: application/json

###
GET http://localhost:5000/api/auth
Accept: application/json

###
GET http://localhost:5000/api/posts
Accept: application/json

###
GET http://localhost:5000/api/users
Accept: application/json

###
GET http://localhost:5000
Accept: application/json

###
